### ISSUE TITLE
Function 'update' is missing

### ISSUE THREAD

**Issue by Daniel-Diaz** [pwrobinson/concurrent-hashtable#1]
[The documentation of `ìnsertIfNotExists`](https://hackage.haskell.org/package/concurrent-hashtable-0.1.5/docs/Data-HashTable.html#v:insertIfNotExists) mentions an `update` function that doesn't seem to exist.

**Comment by pwrobinson** [comment]
Thanks! Fixed by 79cd6d8a3c57e0489485df9e9ae1bdf2db5b1468
