### ISSUE TITLE
slower than HashMap.Strict – what am I doing wrong?

### ISSUE THREAD

**Issue by unhammer** [pwrobinson/concurrent-hashtable#3]
I tried doing a simple frequency list (c.f. https://github.com/benhoyt/countwords ) with streamly at https://github.com/ChrisPenner/wc/compare/master...unhammer:hashtables?expand=1#diff-0e82a3f33e3f6e24a4fb4c5756bd2c8f2ee1edb9037113043a36d2db8fb2076dR43-R77
but concurrent-hashtables performs slower than just the pure HashMap.Strict – am I using it wrong?

To reproduce, grab [wiki.zip](https://github.com/pwrobinson/concurrent-hashtable/files/6156689/wiki.zip) and
```
$ unzip wiki.zip
$ git clone -b  hashtables https://github.com/unhammer/wc
$ cd wc
$ stack build
$ time stack exec wc-exe -- ht wiki >/dev/null  # concurrent-hashtable

real    0m12,149s
user    0m31,028s
sys     0m3,973s
$ time stack exec wc-exe -- hm wiki >/dev/null  # unordered-containers

real    0m7,907s
user    0m21,656s
sys     0m2,437s

$ time mawk -f optimized.awk wiki >/dev/null # https://github.com/benhoyt/countwords/blob/c66dd01d868aa83dc30a9c95226575df1e5e1c5a/optimized.awk

real    0m3,406s
user    0m3,353s
sys     0m0,072s
```
(haven't done anything more benchmarky than `time` since the difference is so stark – HashMap.Strict is consistently nearly 2x faster)

**Comment by pwrobinson** [comment]
In your code, `hm` and `ht` seem to be single-threaded functions, right? 

If so, then it makes perfect sense that `HashMap.Strict` is significantly faster. The concurrent-hashtable package is meant to be used for high-concurrency workloads where you have many different threads accessing the hash table simultaneously. In contrast, `HashMap.Strict` is a pure data structure and hence cannot be shared among multiple threads without placing it into a `TVar` or `MVar`. (In multi-threaded executions, concurrent-hashtable performs significantly better than `HashMap.Strict`, according to the benchmarks.)

**Comment by unhammer** [comment]
They are multithreaded; 

           $ S.aheadly
            $ S.maxThreads numCapabilities

makes it run concurrently (S for [streamly](https://github.com/composewell/streamly/#concurrent-stream-generation)), so both `hm` and `ht` use all 4 cores (I also see it using >300%CPU in htop) – the results for the pure map are unioned as they come in. See also the numbers from `time` which show higher user than real.

**Comment by pwrobinson** [comment]
Ok, thanks for clarifying. If I understand correctly, in `hm`, you're building `numCapabilities` many HashMaps in parallel (each one using a separate thread) and then you use unionWith to merge these hashmaps into a single `HashMap`.  For this kind of workload, `HashMap` is definitely the better choice because there is no possibility that multiple threads may access the same data (which is the scenario that the concurrent-hashtable package is meant to be used for).

**Comment by unhammer** [comment]
OK, so we should expect it to be faster than the package `hashtables` for concurrent workflows, but not faster than `HashMap` when that is possible to use. I'll close this then.
